### ISSUE TITLE
system error code 193 %1 is not a valid win32 application

### ISSUE THREAD

**Issue by briantes** [pashagolub/postgresdac#10]
I have downloaded and install components on Delphi RAD Studio 2010. All worked good. But when I try to connect to a Postgres database, I always get this error: system error code 193 %1 is not a valid win32 application.
I have put all my files in a folder without white spaces and short paths. But nothing works. In design time, if I try to set "connected" to true, I get this error. 
I have tried to connect in runtime, but the same error. I don't know what should I do to solve the problem.

**Comment by pashagolub** [comment]
Hello. 

Do you get this error from RAD Studio? Or when you try to run built application?

Would you please make sure libraries from [Deploy](https://github.com/pashagolub/postgresdac/tree/master/Deploy) folder are accessible directly or via `PATH` envvar.

**Comment by briantes** [comment]
I get this error in RAD Studio 2010 when I try to build the application.

**Comment by pashagolub** [comment]
Would you please make sure libraries from Deploy folder are accessible directly or via PATH envvar

**Comment by briantes** [comment]
Yes, they are.
Prior to use your components. I tried to connect to Postgres with Zeos lib components, but It didn't work due to libpq.dll version problems.
Then I found your components and I tried with they, but I couldn't run my app with your components, due to this error.
Then I tried again with Zeos Lib but using your libpq.dll, and It works.

**Comment by briantes** [comment]
More info. On design time, I can connect to the database and open tables with TPSQLTable. 
When I try to run the app, I get this error.

**Comment by pashagolub** [comment]
Yes, that sounds exactly like a dll mess.

Try to put all dlls from deploy folder right near the application binary. Then it should use them by default

**Comment by briantes** [comment]
Yes. It works now. Thank for your help.
