### ISSUE TITLE
Free (as a beer)?

### ISSUE THREAD

**Issue by laurenz** [pashagolub/postgresdac#15]
The README claims that PostgresDAC is "free (as a beer)".

That usually means that you don't get to use the source, you can only use it without paying license fees, as long as the owner pleases.

Perhaps you should change it to "free ([like free speech, not like free beer][gnu])".

 [gnu]: https://www.gnu.org/philosophy/free-sw.en.html

**Comment by pashagolub** [comment]
Yes, my bad! Thanks!
