### ISSUE TITLE
Using Posgresql version 16, datetime not allowed

### ISSUE THREAD

**Issue by macc2010** [pashagolub/postgresdac#17]
Hello, 

When I use this function : 

function BDETOPSQLStr(Field : TFieldDef): String;

with a Field that is ftDateTime, the function returns the string : DATETIME

When I execute the TPSQLTable.CreateTable it throws me an error from Postgresql server as invalid data type : DATETIME.

If I modify BDETOPSQLStr to return for ftDateTime the string : TIMESTAMP, all works ok.

Thank you.

**Comment by pashagolub** [comment]
Would you please provide a short code snippet for me to test? Thanks
